#
# Edit this file to reflect your setup, then save as 'config.yaml'
#

# Database settings should be pretty self explanatory. Specify type
# according to the available types in the end of this file.
dbi:
    type: postgresql
    host: localhost
    port: 5432
    database: dnscheckng
    user: someuser
    password: somepassword

# When debug is turned on, errors will be more verbose (outputted
# directly in the web view). The about-page will also die if the
# specified customized about page is not found.
debug: 0

# To prevent enumeration of all test data, the test id gets hashed along
# with this salt. Should be a long string.
salt: somelongsaltystringhere

# A custom identifier, for custom about pages.  If the value '_norid' is
# specified, perl will look for a file called 'locale_norid_about.html' in
# the language folder (locale being the chosen locale).
custom_about:

#
# Below are two database specific configurations. This is necessary
# because the database schemas differs slightly between the different
# systems, and the built in functions differs a bit also. This
# configuration should be left untouched in most use cases.
#
# tbl_ are mappings to the database tables
# fun_ are various database engine specific built in functions
#
mysql:
    driver: DBI:mysql:database=%s;hostname=%s;port=%s
    tbl_begin: begin
    tbl_end: end
    tbl_level: level
    fun_time: UNIX_TIMESTAMP(%s)
    fun_now: UNIX_TIMESTAMP()
    fun_time_format: '%s'

postgresql:
    driver: DBI:Pg:database=%s;host=%s;port=%s
    tbl_begin: started
    tbl_end: finished
    tbl_level: class
    fun_time: date_part('epoch', %s)
    fun_now: date_part('epoch', now())
    fun_time_format: to_char(%s, 'YYYY-MM-DD  HH24:MI:SS')
