#
# Edit this file to reflect your setup, then save as 'config.yaml'
#
dbi:
    type: postgresql
    host: localhost
    port: 5432
    database: dnscheckng
    user: someuser
    password: somepassword

# When debug is turned on, errors will be more verbose
debug: 1

# Salt (to prevent enumeration of test data)
salt: somelongsaltystringhere

#
# Below are two database specific configurations. The database schemas
# differs somewhat between postgresql and mysql, therefore this is
# necessary. These standard settings should in most cases not be
# changed.
#
# tbl_ are mappings to the actual database tables
#
mysql:
    tbl_begin: begin
    tbl_end: end
    tbl_level: level

postgresql:
    driver: DBI:Pg:database=%s;host=%s;port=%s
    tbl_begin: started
    tbl_end: finished
    tbl_level: class
