# $Id$

params:
  SOA:EXPIRE_VS_REFRESH: 7
  SOA:MAX_MINIMUM: 86400
  SOA:MIN_EXPIRE: 604800
  SOA:MIN_MINIMUM: 300
  SOA:MIN_REFRESH: 14400
  SOA:MIN_RETRY: 3600
  SOA:MIN_TTL: 3600

loglevels:
  ADDRESS:BEGIN: info
  ADDRESS:END: info
  ADDRESS:INVALID: error
  ADDRESS:PRIVATE_IPV4: error
  ADDRESS:PTR_HOSTNAME_NOT_FOUND: warning
  ADDRESS:PTR_NOT_FOUND: warning
  ADDRESS:RESERVED_IPV4: error
  ADDRESS:RESERVED_IPV6: error
  CONNECTIVITY:ANNOUNCED_BY_ASN: info
  CONNECTIVITY:ASN_COUNT_OK: info
  CONNECTIVITY:ASN_LIST: info
  CONNECTIVITY:BEGIN: info
  CONNECTIVITY:END: info
  CONNECTIVITY:MULTIPLE_ASN: notice 
  CONNECTIVITY:NOT_ANNOUNCED: warning 
  CONNECTIVITY:TOO_FEW_ASN: notice
  CONNECTIVITY:V6_ANNOUNCED_BY_ASN: info
  CONNECTIVITY:V6_ASN_COUNT_OK: info
  CONNECTIVITY:V6_ASN_LIST: info
  CONNECTIVITY:V6_MULTIPLE_ASN: warning
  CONNECTIVITY:V6_NOT_ANNOUNCED: warning 
  CONNECTIVITY:V6_TOO_FEW_ASN: notice
  CONSISTENCY:BEGIN: info
  CONSISTENCY:END: info
  CONSISTENCY:SOA_DIGEST_CONSISTENT: info
  CONSISTENCY:SOA_DIGEST_DIFFERENT: error
  CONSISTENCY:SOA_SERIAL_AT_ADDRESS: info
  CONSISTENCY:SOA_SERIAL_CONSISTENT: info
  CONSISTENCY:SOA_SERIAL_DIFFERENT: warning
  DELEGATION:BEGIN: info
  DELEGATION:END: info
  DELEGATION:EXTRA_NS_CHILD: notice
  DELEGATION:EXTRA_NS_PARENT: error
  DELEGATION:NO_COMMON_NS_NAMES: error
  DELEGATION:POSSIBLE_EXTRA_NS_PARENT: info
  DELEGATION:GLUE_FOUND_AT_CHILD: info
  DELEGATION:GLUE_FOUND_AT_PARENT: info
  DELEGATION:GLUE_MISSING_AT_CHILD: error
  DELEGATION:INCONSISTENT_GLUE: error
  DELEGATION:INZONE_NS_WITHOUT_GLUE: error
  DELEGATION:MATCHING_GLUE: info
  DELEGATION:NOT_FOUND_AT_CHILD: error
  DELEGATION:NOT_FOUND_AT_PARENT: error
  DELEGATION:NO_NS_IPV4: error
  DELEGATION:NO_NS_IPV6: notice
  DELEGATION:NS_AT_CHILD: info
  DELEGATION:NS_AT_PARENT: info
  DELEGATION:NS_HISTORY: info
  DELEGATION:STILL_AUTH: notice
  DELEGATION:TOO_FEW_NS: error 
  DELEGATION:TOO_FEW_NS_IPV4: error
  DELEGATION:TOO_FEW_NS_IPV6: notice
  DELEGATION:BROKEN_UNDELEGATED: critical
  DELEGATION:IPV6_ONLY_AT_PARENT: warning
  DELEGATION:IPV6_ONLY_AT_CHILD: warning 
  DELEGATION:NS_IS_CNAME: error
  DELEGATION:BROKEN_BUT_FUNCTIONAL: error
  DNS:NO_CHILD_NS: error
  DNS:LOOKUP_ERROR: notice
  DNS:NO_ANSWER: notice
  DNS:NO_EDNS: error
  DNS:NO_PARENT: error
  DNS:NO_PARENT_NS: error
  DNS:NXDOMAIN: error
  DNS:SOA_SERVFAIL: error
  DNS:UNQUERIBLE_ADDRESS: notice
  DNSSEC:ADDITIONAL_PROCESSING_BROKEN: error
  DNSSEC:BEGIN: info
  DNSSEC:CHECKING_CHILD: info
  DNSSEC:CHECKING_PARENT: info
  DNSSEC:CHILD_CHECKED: info
  DNSSEC:CHILD_CHECK_ABORTED: info
  DNSSEC:CONSISTENT_SECURITY: info
  DNSSEC:DNSKEY_ALGORITHM_NOT_RECOMMENDED: warning
  DNSSEC:DNSKEY_FOUND: info
  DNSSEC:DNSKEY_MANDATORY_FOUND: info
  DNSSEC:DNSKEY_MANDATORY_NOT_FOUND: error
  DNSSEC:DNSKEY_NOT_FOUND: info
  DNSSEC:DNSKEY_NO_VALID_SIGNATURES: error
  DNSSEC:DNSKEY_SEP: info
  DNSSEC:DNSKEY_SIGNER_UNPUBLISHED: warning
  DNSSEC:DNSKEY_SKIP_PROTOCOL: warning
  DNSSEC:DNSKEY_SKIP_TYPE: warning
  DNSSEC:DNSKEY_VALID_SIGNATURES: info
  DNSSEC:DS_FOUND: info
  DNSSEC:DS_KEYREF_INVALID: info
  DNSSEC:DS_KEYREF_OK: info
  DNSSEC:NO_VALID_DS: error
  DNSSEC:DS_MANDATORY_FOUND: info
  DNSSEC:DS_MANDATORY_NOT_FOUND: error
  DNSSEC:DS_TO_NONSEP: notice
  DNSSEC:DS_TO_SEP: info
  DNSSEC:END: info
  DNSSEC:INCONSISTENT_SECURITY: error
  DNSSEC:MISSING_DS: warning 
  DNSSEC:NO_DS_FOUND: info
  DNSSEC:NO_SIGNATURES: error
  DNSSEC:PARENT_CHECKED: info
  DNSSEC:RRSIG_EXPIRED: warning
  DNSSEC:RRSIG_NOT_YET_VALID: warning
  DNSSEC:RRSIG_VALID: info
  DNSSEC:RRSIG_EXPIRES_AT: info
  DNSSEC:RRSIG_FAILS_VERIFY: warning
  DNSSEC:RRSIG_VERIFIES: info
  DNSSEC:SKIPPED_NO_KEYS: info
  DNSSEC:SOA_NO_VALID_SIGNATURES: error
  DNSSEC:SOA_SIGNER_UNPUBLISHED: warning
  DNSSEC:SOA_VALID_SIGNATURES: info
  DNSSEC:EXTRA_PROCESSING: info
  DNSSEC:NO_EXTRA_PROCESSING: error
  DNSSEC:INCONSISTENT_EXTRA_PROCESSING: error
  DNSSEC:CONSISTENT_EXTRA_PROCESSING: info
  DNSSEC:DNSKEY_ALGORITHM: info
  DNSSEC:DS_ALGORITHM: info
  DNSSEC:ALGORITHM_RESERVED: warning
  DNSSEC:ALGORITHM_UNASSIGNED: warning
  DNSSEC:ALGORITHM_PRIVATE: notice
  DNSSEC:ALGORITHM_OK: info
  FAKEGLUE:BROKEN_INFO: error
  FAKEGLUE:MALFORMED_DS: error
  FAKEGLUE:NO_ADDRESS: error
  HOST:BEGIN: info
  HOST:CNAME_FOUND: error
  HOST:END: info
  HOST:ILLEGAL_NAME: error
  HOST:NOT_FOUND: error
  MAIL:ADDRESS_SYNTAX: notice 
  MAIL:BEGIN: info
  MAIL:DOMAIN_NOT_FOUND: notice 
  MAIL:END: info
  MAIL:HOST_ERROR: notice 
  MAIL:IPV6_ONLY: notice 
  MAIL:MAIL_EXCHANGER: info
  MAIL:DELIVERY_IPV4_OK: info
  MAIL:DELIVERY_IPV4_NOT_OK: warning
  MAIL:DELIVERY_IPV6_OK: info
  MAIL:DELIVERY_IPV6_NOT_OK: notice 
  MAIL:ALL_MX_IN_ZONE: info
  NAMESERVER:AUTH: info
  NAMESERVER:AXFR_CLOSED: info
  NAMESERVER:AXFR_OPEN: notice
  NAMESERVER:AXFR_SKIP: info
  NAMESERVER:BEGIN: info
  NAMESERVER:END: info
  NAMESERVER:HOST_ERROR: error
  NAMESERVER:LEGACY_ID: info
  NAMESERVER:LEGACY_ID_SKIP: info
  NAMESERVER:NOT_AUTH: error
  NAMESERVER:NOT_RECURSIVE: info
  NAMESERVER:NO_TCP: error
  NAMESERVER:NO_UDP: error
  NAMESERVER:NSID: info
  NAMESERVER:NSID_SKIP: info 
  NAMESERVER:RECURSIVE: warning
  NAMESERVER:SKIPPED_IPV4: info
  NAMESERVER:SKIPPED_IPV6: info
  NAMESERVER:TCP_OK: info
  NAMESERVER:UDP_OK: info
  SMTP:BEGIN: info
  SMTP:BANNER: info
  SMTP:CONNECT_FAILED: notice 
  SMTP:END: info
  SMTP:HELLO_FAILED: notice 
  SMTP:MAIL_FROM_REJECTED: notice 
  SMTP:OK: info
  SMTP:RECIPIENT_REJECTED: notice 
  SMTP:TIMEOUT: notice
  SOA:BEGIN: info
  SOA:END: info
  SOA:EXPIRE_OK: info
  SOA:EXPIRE_SMALL: notice
  SOA:EXPIRE_VS_REFRESH: notice
  SOA:FOUND: info
  SOA:MINIMUM_LARGE: notice
  SOA:MINIMUM_OK: info
  SOA:MINIMUM_SMALL: notice
  SOA:MNAME_ERROR: warning
  SOA:MNAME_IS_AUTH: info
  SOA:MNAME_IS_CNAME: info
  SOA:MNAME_NOT_AUTH: warning
  SOA:MNAME_PUBLIC: info
  SOA:MNAME_STEALTH: notice
  SOA:MNAME_VALID: info
  SOA:MULTIPLE_SOA: error
  SOA:NOT_FOUND: error
  SOA:NS_NOT_FOUND: error
  SOA:REFRESH_OK: info
  SOA:REFRESH_SMALL: notice
  SOA:RETRY_OK: info
  SOA:RETRY_SMALL: notice
  SOA:RETRY_VS_REFRESH: notice
  SOA:RNAME_DELIVERABLE: info
  SOA:RNAME_SYNTAX: error
  SOA:RNAME_UNDELIVERABLE: warning
  SOA:SKIPPED_IPV4: info
  SOA:SKIPPED_IPV6: info
  SOA:TTL_OK: info
  SOA:TTL_SMALL: notice
  SOA:SERIAL_IS_ZERO: warning
  ZONE:BEGIN: info
  ZONE:END: info
  ZONE:FATAL_DELEGATION: critical
  ZONE:FATAL_NO_CHILD_NS: critical
  ZONE:INVALID_NAME: critical
